isEnabled: true
isRestricted: false
messages:
  added: '&aПользователь %player добавлен в белый список.'
  alreadyInList: '&cПользователь %player уже в белом списке.'
  removed: '&aПользователь %player удалён из белого списка.'
  cleared: '&aБаза players пересоздана.'
  error: '&cЧто-то пошло не так.'
  wrongUsage: '&cНеправильное использование. /wl <add/remove/clear>'
  kickMessage: '&cВас нет в вайтлисте. Оставьте заявку на https://marla.su/quitovsky'
  reloaded: '&aКонфиг обновлён.'
  pluginEnabled: '&aВайтлист включен.'
  pluginDisabled: '&cВайтлист выключен.'
  kickedRestricted: "&cВход временно разрешен только для администраторов."
  restrictedDisabled: "&cОграниченный режим выключен."
  restrictedEnabled: "&aОграниченный режим (вход только для администраторов) включен."