name: QWhitelist
version: '${project.version}'
main: qtv.qwhitelist.QWhitelist
commands:
  qwhitelist:
    aliases:
      - wl
    permission: qwhitelist.edit
    description: Edit players in QWhitelist